name: mrm-module-test
recipe: drupal9

config:
  php: '8.2'
  via: nginx
  webroot: web
  drush: "*"
  xdebug: false

services:
  database:
    type: mariadb:10.5.13
    portforward: 23569

events:
  post-start:
    - appserver: cd $LANDO_MOUNT && composer install
